spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hotel_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: hxj
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
 mapper-locations: classpath*:mapper/*Mapper.xml
server:
  port: 8888
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8